name: Android CI

on:
  push:
    branches: [ "master", "dev" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      KEYSTORE_PATH: ${{ github.workspace }}/keystore.jks
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Decode and Save Keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > $GITHUB_WORKSPACE/keystore.jks
        chmod 600 $GITHUB_WORKSPACE/keystore.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Signed APK
      run: ./gradlew assembleRelease

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')  # Runs only for tag pushes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Upload APK as GitHub Release
      - name: Upload APK to GitHub Releases
        uses: actions/upload-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            path: app/build/outputs/apk/release/app-release.apk
            name: ${{ github.ref }}